### ISSUE TITLE
Feature request: save calculation steps

### ISSUE THREAD

**Issue by E-Brons** [cryptii/cryptii#39] opened 2019-03-14 07:16 UTC
A user may combine some complicated steps and want to save this combination for future use.
Use case example: User enters a private key + URL to generate passwords

Since the website doesn't support login (consider...), I would suggest saving the combination in the URI: Add a button to generate a permanent link to the configuration will generate something like
https://cryptii.com/#config=...

**Comment by ffraenz** [comment] 2019-03-17 12:17
Duplicate of #19

Please have a look at the discussion in #19.

**Comment by ffraenz** [comment] 2019-03-17 12:17
Duplicate of #19

**Comment by ffraenz** [comment] 2019-03-17 12:19
Please have a look at the discussion over at issue #19.

**Closed by ffraenz** 2019-03-17 12:19 UTC
Labels: duplicate

**Comment by E-Brons** [comment] 2019-03-18 09:31
> Please have a look at the discussion over at issue #19.

Sorry for the duplication! Thanks!
