### ISSUE TITLE
Feature Request: "Share this via URL"

### ISSUE THREAD

**Issue by HourGlss** [cryptii/cryptii#42] opened 2019-04-22 12:45 UTC
It would be great to be able to share the chain I have made with someone else.

**Comment by ffraenz** [comment] 2019-04-22 17:23
Duplicate of #19

**Comment by ffraenz** [comment] 2019-04-22 17:24
Hi @HourGlss, please have a look at the discussion over at #19. Thank you!

**Closed by ffraenz** 2019-04-22 17:23 UTC
